Add recert dry-run as a pre-check to validate seed SNO cluster
leo8a/ibu-imager pull request #9
Opened 2023-10-20 15:19 UTC by leo8a

This is a PR for discussing the triggering of the recert --dry-run (as a pre-check) from Imager.

/cc @omertuc @tsorya @donpenney

2023-10-20 15:24 UTC, leo8a commented
In my latest iteration, I saw this issue when triggering the tool.

```
time="2023-10-20 15:05:40" level=debug msg="Running command: nsenter --target 1 --cgroup --mount --ipc --pid -- podman run --rm --name recert --network=host --privileged --authfile /var/lib/kubelet/config.json -v /var/tmp/backup:/backup -v /etc/kubernetes:/kubernetes -v /var/lib/kubelet:/kubelet -v /etc/machine-config-daemon:/machine-config-daemon jumphost.inbound.vz.bos2.lab:8443/edge-infrastructure/recert:latest --etcd-endpoint localhost:2379 --static-dir /kubernetes --static-dir /kubelet --static-dir /machine-config-daemon --extend-expiration --dry-run --summary-file-clean /backup/recert.summary"
Error: scanning and recertification

Caused by:
    0: processing discovered objects
    1: regenerating crypto
    2: re-signing cert with subject CN=system:open-cluster-management:cluster:zt-sno2:addon:config-policy-controller:agent:config-policy-controller, O=system:authenticated, O=system:open-cluster-management:addon:config-policy-controller, O=system:open-cluster-management:cluster:zt-sno2:addon:config-policy-controller
    3: could not find matching akid key identifier in chain
time="2023-10-20 15:06:32" level=error msg="An error occurred: exit status 1"
```

Seems that a clean up (see [reference](https://github.com/donpenney/sno-relocation-poc/commit/f47bb59f1bd4be526fb592370d7a6f4230998364)) step is required before running the recert tool. 

(When possible) let's discuss whether this cleanup / preparation step could be done by another component or by Imager.

2023-10-20 15:40 UTC, omertuc requested changes

2023-10-20 15:40 UTC, omertuc commented on cmd/create.go
> +		return
This seems like a good place to use `log.Fatal`

```suggestion
		log.Fatal"*** Please provide a valid container image for the recert tool *** \n")
```

But maybe in a separate PR, because this pattern is already commonplace in the codebase

2023-10-20 15:40 UTC, omertuc commented on cmd/create.go
> +	//
If you find yourself needing to write giant comment headers like this, maybe it's a good sign you want to stuff the code it envelopes in a separate, well-named method

2023-10-20 15:40 UTC, omertuc commented on cmd/create.go
> +	if _, err = os.Stat("/var/tmp/recert.done"); os.IsNotExist(err) {
I don't think we ever want to skip running recert before doing the snapshot, even if it was done before, things might have changed accidentally between imager invocations.

2023-10-20 15:40 UTC, omertuc commented on cmd/create.go
> +		check(err)
As much as I hate Go error checking and understand your motivation for creating `check`, idiomatic Go usually doesn't hide error checking behind fatal functions like this. It's best to wrap err and return it to the caller:
```go
if err != nil {
    return fmt.Errorf("running recert etcd: %w", err)    
}
```

Then the fatal logging of the error should be done by the topmost caller - the one who has no caller to further propagate the error to. And since errors are wrapped when you use %w, you get a nice "trace" of what happened to cause the error, instead of just a vague error without context

2023-10-20 15:40 UTC, omertuc commented on cmd/utils.go
> +	return ""
```suggestion
	log.Fatalf("etcd container image not found in the YAML.")
```

2023-10-23 19:33 UTC, leo8a commented
Just rebased and refactored this PR to use the new Imager workflow.

2023-10-24 08:48 UTC, tsorya commented on cmd/create.go
> +		return
no need for return as fatal will exit the program

2023-10-24 08:49 UTC, tsorya commented on cmd/create.go
>  		return
same, why not to return the message with fatal?

2023-10-24 08:50 UTC, tsorya commented on internal/seed_creator/seed_creator.go
> +	"gopkg.in/yaml.v3"
move import to lower block in order to be aligned with import format

2023-10-24 08:52 UTC, tsorya commented on internal/seed_creator/seed_creator.go
> +		log.Fatalf("Error unmarshaling YAML: %v\n", err)
fatal should not be used inside objects and functions, just return and error please.

2023-10-24 08:53 UTC, tsorya commented on internal/seed_creator/seed_creator.go
> +	return ""
I assume no image is a bad option right? why it is not error?

2023-10-24 08:55 UTC, tsorya commented on internal/seed_creator/seed_creator.go
> +	s.log.Debug("Run unauthenticated etcd server for recert dry-run")
why not info?

2023-10-24 08:57 UTC, tsorya commented on internal/seed_creator/seed_creator.go
> +func (s *SeedCreator) runRecertDryRun() error {
Maybe we can move it to some new object and call it validations? or something better? and leave creator just for create part?

2023-10-27 09:01 UTC, leo8a commented
Closing since the tool is now part of the lifecycle-agent project, active development has been moved to https://github.com/openshift-kni/lifecycle-agent.

@omertuc @tsorya - Many thanks for your comments and suggestions! ++

2023-10-27 09:01 UTC, closed without merging